export const PLANTS = [
  {
    id: "ora-pro-nobis",
    nome: "Ora-pro-nóbis",
    cientifico: "Pereskia aculeata",
    descricao: "Planta trepadeira rica em proteínas, fibras e minerais, considerada uma PANC muito nutritiva.",
    receitas: ["Sopa de ora-pro-nóbis", "Torta de ora-pro-nóbis", "Refogado de ora-pro-nóbis"],
    img: "/images/plants/ora-pro-nobis.jpg",
  },
  {
    id: "peixinho-da-horta",
    nome: "Peixinho-da-horta",
    cientifico: "Stachys byzantina",
    descricao: "Folhas aveludadas, sabor herbáceo, muito usada empanada por lembrar peixe frito.",
    receitas: ["Peixinho-da-horta empanado", "Tempurá de peixinho-da-horta", "Lasanha de peixinho-da-horta"],
    img: "/images/plants/peixinho-da-horta.jpg",
  },
  {
    id: "moringa",
    nome: "Moringa",
    cientifico: "Moringa oleifera",
    descricao: "Árvore originária da Índia, rica em vitaminas, minerais e antioxidantes, usada em chás e sopas.",
    receitas: ["Chá de moringa", "Sopa de moringa", "Salada com folhas de moringa"],
    img: "/images/plants/moringa.jpg",
  },
  {
    id: "beldroega",
    nome: "Beldroega",
    cientifico: "Portulaca oleracea",
    descricao: "Planta rasteira rica em ômega-3, antioxidantes e fibras, usada em saladas e sopas.",
    receitas: ["Arroz de beldroega", "Sopa de beldroega", "Refogado de beldroega"],
    img: "/images/plants/beldroega.jpg",
  },
  {
    id: "taioba",
    nome: "Taioba",
    cientifico: "Xanthosoma taioba",
    descricao: "Hortaliça da família Arácea, fonte de ferro, cálcio e vitamina A, muito usada na culinária mineira.",
    receitas: ["Bolinho de taioba", "Taioba refogada", "Charutinho de taioba"],
    img: "/images/plants/taioba.jpg",
  },
  {
    id: "capuchinha",
    nome: "Capuchinha",
    cientifico: "Tropaeolum majus",
    descricao: "Flor comestível ornamental e nutritiva, com propriedades medicinais e sabor levemente picante.",
    receitas: ["Patê de capuchinha e grão-de-bico", "Salada de capuchinha", "Arroz com flores de capuchinha"],
    img: "/images/plants/capuchinha.jpg",
  },
];
