import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import PageTransition from "@/components/transition/page-trans";
import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/footer";
=======
import React from 'react';
import PageTransition from "@/components/transition/page-trans";
import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/footer";
import { AuthProvider } from '@/components/auth/AuthProvider';
import AuthGuard from '@/components/auth/AuthGuard';
>>>>>>> origin/pancjoao

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Dashboard",
  description: "Dashboard da Horta da Fatec PANC",
>>>>>>> origin/pancjoao
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} h-full
      >
        <Nav />
        <PageTransition>
          {children}
        </PageTransition>
        <Footer />
=======
    <html lang="pt-BR">
      <body>
        <AuthProvider>
          <Nav />
          <AuthGuard>{children}</AuthGuard>
          <Footer />
        </AuthProvider>
>>>>>>> origin/pancjoao
      </body>
    </html>
  );
}
